### ISSUE TITLE
Images in help book not showing correctly

### ISSUE THREAD

**Issue by pkrll** [Saturn-Five/ComicZipper#80]
The two vector images in the "Drag & Drop" section does not display correctly.

![screen shot 2015-10-26 at 18 30 55](https://cloud.githubusercontent.com/assets/140205/10739658/01e0655a-7c1e-11e5-93f6-eb56097f133e.png)

**Comment by mikemcduffie** [comment]
Annotating here for record. 
Appears to be a bug in the 10.10.x Help viewer with displaying SVG images containing PNGs. SVG images with embedded PNG work in the 10.11 Help viewer. I'll generate PNGs and change the MD file.
