### ISSUE TITLE
2.6.x terminates on auto-quit before DeleteFolders operation (if both are enabled)

### ISSUE THREAD

**Issue by mikemcduffie** [Saturn-Five/ComicZipper#81]
I missed this somehow, so maybe unit tests are needed. ;)

The last part of the method `compressOperation` in CZComicZipper.m is not being run on the last item operation after the `[self.delegate ComicZipper:self didFinishItemAtIndex:index]` statement:

```     
        // Remove the folders (if setting is on) after compression
        if (self.operations.operationCount == 0) {
            NSLog(@"deleteDolders");
            [self deleteFolders];
        }
```
The app terminates before the condition is evaluated on the last item when `self.operations.operationCount == 0` would have been true. 

I traced it back through `didFinishItemAtIndex` to `reloadDataForRow` to `updateCount` which since `numberOfItemsToCompress > 0` is not true calls `postNotification:CZCompressionDoneNotification` -> `didReceiveNotification CZCompressionDoneNotification` to `compressionDidFinish`  which terminates the app before it can return to `compressOperation`.

Since this isn't a simple line or two of code to correct, I'm passing this you to decide how you want to handle the logic. 

One thing that strikes me is whether moving all the folders at the end of operations is better than moving each folder after the individual compression operation. It wouldn't have resolved the issue of moving the last folder, but it would made it easier to figure what was going on. 

I ran down a few false paths troubleshooting plist settings, etc. It appears that the plist is now bifurcated between `Application Support` and `Preferences` which threw me off for a bit. But that may be an artifact of running different versions of the app — pre-2.6 & 2.6.x. That and the last few OS versions cache settings so helpfully — NOT.

**Comment by pkrll** [comment]
Fixed.

It is better to do one operation, than potentially hundreds of operations. So yes, it is better to delete all folders at the end.

Remove the plist in app support. It's from before I moved to NSUSerDefaults
