### ISSUE TITLE
System alert sound is clipped on auto-quit

### ISSUE THREAD

**Issue by mikemcduffie** [Saturn-Five/ComicZipper#82]
The completion alert sound when CZ is the front app is clipped when auto-quit is enabled. Presumably it doesn't finish plating before the app terminates. Notification Center alert is fine as expected as it's handled by the system. 

Can the play sound action be handed off to the system for completion after app terminated or the app window hidden and a terminate be delayed until sound completed? Do you get notified when completed? Otherwise could be an issue for sounds longer than the system default.

**Comment by pkrll** [comment]
Don't know if that actually is possible. I think the best solution is to always show a notification when auto quit is on. That way the user will always know what is happening.

**Comment by mikemcduffie** [comment]
That works. Notification on auto-quit makes sense as the interface is no longer present to indicate number of items processed, etc.

**Comment by mikemcduffie** [comment]
I would tie it to the background state settings for notification, i.e just one settings (notifications on/off).

**Comment by pkrll** [comment]
Yup, done, committed.
